version: "2.3"
services:
  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/Laxus0212/fridge-management-backend
      RUNNER_NAME: fridge-backend-runner
      RUNNER_TOKEN: $${{ secrets.SYNOLOGY_GITHUB_TOKEN }}
      RUNNER_WORKDIR: /tmp/github-runner
      RUNNER_SCOPE: repo
    volumes:
      - "/volume1/docker/docker.sock:/var/run/docker.sock"
      - "/volume1/docker/github-runner:/tmp/github-runner"
