GRANT ALL PRIVILEGES ON *.* TO 'varadi'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;

SET GLOBAL event_scheduler = ON;
