name: CI/CD Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Repository klónozása
        uses: actions/checkout@v3

      - name: Docker image építése
        run: |
          docker build -t fridge-management-backend:${GITHUB_REF#refs/tags/} .
        env:
          DOCKER_BUILDKIT: 1

      - name: Docker image push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push fridge-management-backend:${GITHUB_REF#refs/tags/}

      - name: Konténer újraindítása a NAS-on
        run: |
          sshpass -p "${{ secrets.NAS_PASSWORD }}" ssh -o StrictHostKeyChecking=no github-user@varadinas "docker pull fridge-management-backend:${GITHUB_REF#refs/tags/} && docker-compose -f /volume1/docker/fridge-management-backend/docker-compose.yml up -d"
