name: CI/CD Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract tag
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: laxus0212/fridge-management-backend:${{ env.TAG_NAME }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy_backend_dev:
    runs-on: self-hosted
    needs: build-backend
    if: contains(github.ref, '-DEV')
    steps:
      - name: Extract tag
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: SSH to NAS and deploy DEV
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NAS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa github-user@varadinas "
          export PATH=\$PATH:/usr/local/bin
            docker --version
            docker-compose --version
          
            docker pull laxus0212/fridge-management-backend:${{ env.TAG_NAME }}
            echo \"IMAGE_VERSION=${{ env.TAG_NAME }}\" > /volume1/docker/fridge-management-backend/dev/.env
            docker-compose -f /volume1/docker/fridge-management-backend/dev/docker-compose.dev.yml up -d
          "

  deploy_backend_prod:
    runs-on: self-hosted
    needs: build-backend
    if: "!contains(github.ref, '-DEV')"
    steps:
      - name: Extract tag
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: SSH to NAS and deploy PROD
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NAS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa github-user@varadinas "
          export PATH=\$PATH:/usr/local/bin
            docker --version
            docker-compose --version
          
            docker pull laxus0212/fridge-management-backend:${{ env.TAG_NAME }}
            echo \"IMAGE_VERSION=${{ env.TAG_NAME }}\" > /volume1/docker/fridge-management-backend/prod/.env
            docker-compose -f /volume1/docker/fridge-management-backend/prod/docker-compose.prod.yml up -d
          "
