name: CI/CD Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Repository klónozása
        uses: actions/checkout@v3

      - name: Extract tag for Windows
        run: |
          $env:TAG_NAME = "${{ github.ref }}" -replace 'refs/tags/', ''
          echo "TAG_NAME=$env:TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Docker image építése
        run: |
          $TAG_NAME = $env:TAG_NAME
          docker build -t laxus0212/fridge-management-backend:$TAG_NAME .
        shell: pwsh
        env:
          DOCKER_BUILDKIT: 1

      - name: Docker image push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
          docker push laxus0212/fridge-management-backend:${{ env.TAG_NAME }}

      - name: Konténer újraindítása a NAS-on SSH kulccsal
        run: |
          # SSH könyvtár és kulcs beállítása
          mkdir -p ~/.ssh
          echo "${{ secrets.NAS_SSH_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
          # Kapcsolódás a NAS-hoz és a konténer frissítése
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa github-user@varadinas "
            export PATH=\$PATH:/usr/local/bin
            docker --version
            docker-compose --version
            docker pull laxus0212/fridge-management-backend
            docker-compose -f /volume1/docker/fridge-management-backend/docker-compose.yml up -d
          "

